# Generated by Django 6.0.3 on 2026-07-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings_total_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='installments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='registration_fee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
